상세페이지 제품 보여주기
wecode-bootcamp-korea/37-1st-HUSH-backend pull request #10
Opened 2022-09-22 06:21 UTC by ninetysixHoon

## :: 최근 작업 주제 (하나 이상의 주제를 선택해주세요.)
- [ o ] 기능 추가
- [ ] 리뷰 반영
- [ ] 리팩토링
- [ ] 버그 수정
- [ ] 컨벤션 수정

<br />

## :: 구현 목표 (해당 브랜치에서 구현하고자 하는 하나의 목표를 설정합니다.)
- 아이디, 비밀번호 입력창을 사용한 로그인 기능 구현 (예시)

<br />

## :: 구현 사항 설명 (작업한 내용을 상세하게 기록합니다.)
1. 로그인 입력 데이터 유효성 검사 (예시 - 프론트)
- 입력창에 변화가 일어날 때 마다 유효성 검사 함수가 실행된다.
- 유효성 검사 함수의 반환값(boolean)에 따라 버튼의 배경색과 disabled 속성이 변화한다.
- 테스트 방법 : `/login` 페이지 이동 >>> 로그인 input 데이터 입력

2. 로그인 데이터 처리 (예시 - 백엔드)
- 조건문과 정규식을 이용한 email과 password 유효성 검사를 진행
- 유효섬 검사를 통과하지 못 할 경우 에러 메시지를 반환 예외 처리 구현

<br />

## :: 성장 포인트 (해당 기능을 구현하며 고민했던 사항이나 새로 알게된 부분, 어려웠던 점 등을 작성합니다.)
- 사용자가 발생시킬 수 있는 다양한 예외 케이스에 대해 고민하게 되었습니다. (예시)
- 문자열 데이터 입력 시 마지막에 빈 문자열이 포함되어 있는 경우 데이터 처리가 올바르게 되지 않아 유효성 검사에 빈 문자열 제거하는 로직을 추가하였습니다. (예시)

<br />

## :: 기타 질문 및 특이 사항
- 함수 로직이 너무 긴 것 같습니다. 좀 더 효율적인 방법이 없을지 궁금합니다.(예시)

2022-09-22 08:21 UTC, bigfanoftim requested changes

2022-09-22 08:21 UTC, bigfanoftim commented on app.js
> +start();
이 부분은 기존에 있던 코드를 사용해도 충분한데 굳이 따로 바꾸신 이유가 있을까요?

2022-09-22 08:21 UTC, bigfanoftim commented on controllers/productsController.js
> +    // console.log(req.body)
불필요한 주석 다 지워주세요!

2022-09-22 08:21 UTC, bigfanoftim commented on models/dataSource.js
> +    database: process.env.TYPEORM_NAME
팀원들과 함께 사용하던 config는 수정하지 말아주세요. 바꾸는 것이 아니라 본인이 맞춰야 합니다.

2022-09-22 08:21 UTC, bigfanoftim commented on routes/productsRouter.js
> +
불필요한 주석 다 지워주세요!

2022-09-23 02:26 UTC, bigfanoftim commented
@ninetysixHoon @dyjeong576  
여러분 PR을 올리실 때에는 직접 본인이 작성한 Pull Request가 리뷰를 받을 준비가 되었는지 제일 먼저 확인하셔야 합니다.

1. Conflict를 해결

  <img width="458" alt="image" src="https://user-images.githubusercontent.com/62135254/191881593-38e77f1a-e57a-4e99-975f-7a7af84e65f3.png">

2. PR 페이지에 있는 `Files changed`를 눌러 잘못된 것은 없는지 확인


해결이 힘들거나 어떻게 해야 할지 모르겠다면 Comment로 남겨주세요.

2022-09-23 04:00 UTC, ninetysixHoon commented
Confilct 해결 방법을 잘 모르겠습니다.

2022-09-23 08:13 UTC, bigfanoftim approved these changes
LGTM 👍👍👍

2022-09-23 08:13 UTC, merged