[정다영- HUSH] First Project 구매페이지_구매하기API 구현
wecode-bootcamp-korea/37-1st-HUSH-backend pull request #15
Opened 2022-09-22 15:36 UTC by dyjeong576

## :: 최근 작업 주제 (하나 이상의 주제를 선택해주세요.)
- [X] 기능 추가
- [ ] 리뷰 반영
- [ ] 리팩토링
- [ ] 버그 수정
- [ ] 컨벤션 수정

<br />

## :: 구현 목표 (해당 브랜치에서 구현하고자 하는 하나의 목표를 설정합니다.)
- 구매페이지에서 구매하기 구현

<br />

## :: 구현 사항 설명 (작업한 내용을 상세하게 기록합니다.)
1. order 테이블에 order 아이디를 생성
2. cart 테이블에 구매자가 체크한 제품들의 목록만을 추출해서 product 변수에 담음
3. orderItems 테이블에 생성한 order 아이디와 제품들을 담음
4. product의 재고를 사용자가 구매한 만큼 차감
5. cart 테이블 중 사용자가 구매한 제품만 삭제
6. 사용자 포인트 차감
7.  typeorm 트랜잭션을 적용하여 위의 query 오류가 rollback함

<br />

## :: 성장 포인트 (해당 기능을 구현하며 고민했던 사항이나 새로 알게된 부분, 어려웠던 점 등을 작성합니다.)
- 한 api에 query문이 많을 경우 query 순서를 많이 고민해봤습니다..
- db에 unique키가 많이 필요하다는 걸 깨달았습니다.
- 중간 오류시 롤백하는 트랜잭션의 원리를 배웠고, 이를 코드로 구현하는 방법을 알게 되었습니다..

<br />

## :: 기타 질문 및 특이 사항
- 사용자의 포인트가 차감되면 이를 다시 프론트에 전달해야 하는데 그 방법을 잘 모르겠습니다ㅠ  body에 실어주는게 맞을까요? 사용자의 포인트는 항상 웹페이지 상단에 띄어져야 하는데 그렇다면 모든요청시 항상 사용자의 포인트를 실어주는게 맞나 궁금합니다.. 예를 들어 구매하기 버튼을 누르면 다음페이지로 넘어가는데 그 때 res body에 사용자의 포인트를 실어주는게 맞을까요?

2022-09-23 17:31 UTC, dyjeong576 commented
멘토님 app.js는 초기셋팅인데 app.js가 수정된 상태로 merge가 나서 충돌이 많이 일어납니다.
현재 브랜치에서 app.js을 원래대로 돌린 후에 pr을 요청하면 반영이 될까요? 
브랜치를 많이 만들어놨는데 app.js가 변경되서 conflict가 많이 납니다....ㅠ

2022-09-26 01:58 UTC, dyjeong576 commented
멘토님 merge된 app.js가 수정되었는데 다시 원복가능할까요?

2022-09-26 02:43 UTC, bigfanoftim commented
> 멘토님 merge된 app.js가 수정되었는데 다시 원복가능할까요?

수정된 app.js를 원상복귀하려는 이유가 무엇인가요??

2022-09-26 02:47 UTC, bigfanoftim commented
> 트랜잭션을 미들웨어로 구현하고 싶은데 방법을 도저히 모르겠습니다..

트랜잭션은 DB에서 지원하는 기능으로 Dao에서 DataSource 객체 내 메소드를 활용해 해결하시면 될 것 같습니다!

> 사용자의 포인트가 차감되면 이를 다시 프론트에 전달해야 하는데 그 방법을 잘 모르겠습니다ㅠ body에 실어주는게 맞을까요? 사용자의 포인트는 항상 웹페이지 상단에 띄어져야 하는데 그렇다면 모든요청시 항상 사용자의 포인트를 보내는게 맞나 궁금합니다.. 예를 들어 구매하기 버튼을 누르면 다음페이지로 넘어가는데 그 때 res body에 사용자의 포인트를 실어주는게 맞을까요?

구매 완료시 response body로 포인트를 넘겨줘서 해결한다면 다른 문제가 발생합니다. 예를 들어 구매 완료를 거치지 않고 웹페이지를 접속한 사람에 대해서는 그에 대한 값을 알 수가 없습니다. 따라서 애초에 화면에 그려지는 데이터가 user info기 때문에 해당 부분에 대한 데이터를 받아올 수 있는 userInfo API를 만드시면 됩니다.

2022-09-26 04:03 UTC, dyjeong576 commented
> > 멘토님 merge된 app.js가 수정되었는데 다시 원복가능할까요?
> 
> 수정된 app.js를 원상복귀하려는 이유가 무엇인가요??

app.js 내에 불필요한 코드들이 있는 거 같습니다. 그리고 수정이 된 이유는 뭔가요?

2022-09-27 03:03 UTC, bigfanoftim requested changes

2022-09-27 03:03 UTC, bigfanoftim commented on controllers/orderController.js
> +  const { productId } = req.query;
POST Method이니 필요한 데이터 전부 body로 넣어주셔도 좋을 것 같습니다.

2022-09-27 03:03 UTC, bigfanoftim commented on models/orderDao.js
> +            )`,
for문 대신 bulk insert로 진행해 주세요!

mysql bulk insert 검색하시면 금방 해결하실 수 있을 겁니다!

2022-09-27 03:03 UTC, bigfanoftim commented on models/orderDao.js
> +         ,
여기도 for문 대신 전부 삭제하는 방법을 고려해 보세요!

2022-09-27 12:52 UTC, dyjeong576 commented on models/orderDao.js
> +            )`,
해결했습니다.

2022-09-27 12:52 UTC, dyjeong576 commented on models/orderDao.js
> +         ,
해결했습니다.

2022-09-28 01:58 UTC, bigfanoftim approved these changes

2022-09-28 01:58 UTC, merged