[정다영 - HUSH] First Project 유저의 찜목록 삭제하기
wecode-bootcamp-korea/37-1st-HUSH-backend pull request #7
Opened 2022-09-21 16:47 UTC by dyjeong576

## :: 최근 작업 주제 (하나 이상의 주제를 선택해주세요.)
- [x] 기능 추가
- [ ] 리뷰 반영
- [ ] 리팩토링
- [ ] 버그 수정
- [ ] 컨벤션 수정

<br />

## :: 구현 목표 (해당 브랜치에서 구현하고자 하는 하나의 목표를 설정합니다.)
- 유저의 찜목록 삭제
<br />

## :: 구현 사항 설명 (작업한 내용을 상세하게 기록합니다.)
1. 찜목록 페이지에서 체크박스에 체크된 제품들의 아이디를 프론트에서 body에 실어 요청을 보내면 찜목록 테이블에서 삭제

<br />

## :: 성장 포인트 (해당 기능을 구현하며 고민했던 사항이나 새로 알게된 부분, 어려웠던 점 등을 작성합니다.)
- x
<br />

## :: 기타 질문 및 특이 사항
- delete 상태코드는 204인데 이런 경우 응답 json이 안 보내지는 거 같습니다... 
- 프론트가 body에 삭제할 제품의 아이디를 실어서 줄 수 있나요?
- dao내에서 for문으로 데이터를 여러 번 넣고 있는데 더 나은 방법이 있을까요?

2022-09-22 07:25 UTC, bigfanoftim commented
> delete 상태코드는 204인데 이런 경우 응답 json이 안 보내지는 거 같습니다...

204 status code는 No Content를 의미하기 때문에 json에 데이터를 넣고 response하더라도 실제로 클라이언트가 받을 수 없습니다!!
애초에 의도 자체가 그렇기 때문에 만약 response body를 꼭 넘겨줘야 할 필요가 있다면 다른 status code를 활용해 주세요!

2022-09-22 07:28 UTC, bigfanoftim commented
이 PR도 main에서 auth merge 받으시고 수정해 주세요!

2022-09-23 06:31 UTC, bigfanoftim requested changes

2022-09-23 06:31 UTC, bigfanoftim commented on models/userDao.js
> +<<<<<<< HEAD
```suggestion
```

👀 :( 

푸시전에 꼭 테스트 해주세요!

2022-09-23 06:49 UTC, dyjeong576 commented on models/userDao.js
> +<<<<<<< HEAD
넵..ㅠ

2022-09-23 07:05 UTC, dyjeong576 commented on models/userDao.js
> +<<<<<<< HEAD
멘토님 테스트 성공 후  push 다시 했습니다. 죄송합니다. ㅠㅠ

2022-09-23 08:08 UTC, bigfanoftim requested changes

2022-09-23 08:08 UTC, bigfanoftim commented on controllers/userController.js
> +  const { products } = req.body;
```JavaScript
// Endpoint : :3000/users/likes?product_id=1&product_id=2
// 여기서 product_id=1,2 이렇게 쓰면 나중에 String으로 "1,2"를 받게 되어 다시 리스트로 변환하는 코드를 작성해야 합니다. 그에 맞게 다수의 쿼리 파라미터를 사용할 때에는 &를 사용해 주세요.

const productIds = req.query.productId
// 이 부분 프로퍼티명이 저도 헷갈려서 req.query가 맞는지 확인이 필요하긴 합니다. 한번 직접 확인해 주세요!
```

2022-09-23 08:08 UTC, bigfanoftim commented on models/userDao.js
> +        `,
```JavaScript
`
  DELETE FROM likes
  WHERE user_id = ?
  AND product_id = (?)
`, [ userId, product_ids ]
```

2022-09-23 16:48 UTC, dyjeong576 commented on controllers/userController.js
> +  const { products } = req.body;
수정했습니다.

2022-09-23 17:01 UTC, dyjeong576 commented on models/userDao.js
> +        `,
product_ids를 string으로 변환했음에도 불구하고 오류가 납니다. (예를들어 product_ids = "3,4") 
오류가 나지 않기 위해서는 preparedStatement 형식이 아닌 ${product_id} 형식으로 직접 넣어줘야 합니다.. 
뭔가 이상한 거 같아 다시 for문을 적용했습니다.

질문이 추가로 있습니다.
카트에 제품 아이디가 있는지 조회한 후 만약 아이디가 없는데 삭제를 시도한다면 에러로 처리하려고 합니다. 이 때
select문에서도 for문을 사용하지 않고 2개 이상의 데이터들을 조회할 수 있나요?

2022-09-26 01:00 UTC, bigfanoftim commented on models/userDao.js
> +        `,
다영님! 죄송해요ㅠ 제가 작성해드린 예시 코드에 문제가 있었네요~

```JavaScript
`
  DELETE FROM likes
  WHERE user_id = ?
  AND product_id IN (?)
`, [ userId, product_ids ]
```

`=`이 아니라 `IN`이어야 합니다!

2022-09-26 01:00 UTC, bigfanoftim commented on models/userDao.js
> +        `,
괄호 등 정확한 형태는 확실치 않으니 한번 확인이 필요합니다~

2022-09-26 01:02 UTC, bigfanoftim requested changes

2022-09-26 01:02 UTC, bigfanoftim commented on controllers/userController.js
> +  const { productId } = req.query;
`const productIds = req.query.productId` 가 어떨까요?

id의 리스트를 받아오는 것이기 때문에 다음과 같이 작성하는게 더 좋을 것 같습니다!

2022-09-26 01:02 UTC, bigfanoftim commented on models/userDao.js
> +			product_id = ?`,
이 부분은 Comment로 남겼으니 확인해 주세요!

2022-09-26 02:40 UTC, bigfanoftim approved these changes
LGTM 👍

2022-09-26 02:40 UTC, merged