[정다영 - HUSH] First Project 찜목록 추가하기
wecode-bootcamp-korea/37-1st-HUSH-backend pull request #8
Opened 2022-09-22 04:24 UTC by dyjeong576

## :: 최근 작업 주제 (하나 이상의 주제를 선택해주세요.)
- [x] 기능 추가
- [ ] 리뷰 반영
- [ ] 리팩토링
- [ ] 버그 수정
- [ ] 컨벤션 수정

<br />

## :: 구현 목표 (해당 브랜치에서 구현하고자 하는 하나의 목표를 설정합니다.)
-  상품페이지내에서 찜목록 추가하기

<br />

## :: 구현 사항 설명 (작업한 내용을 상세하게 기록합니다.)
1. 상품페이지 내에서 하트를 누르면 찜목록에 추가
2. 만약 찜목록에 이미 존재한다면 LIKE_AREADY_EXUSTS 를 응답
3. 존재하지 않다면 찜리스트에 제품 추가!

<br />

## :: 성장 포인트 (해당 기능을 구현하며 고민했던 사항이나 새로 알게된 부분, 어려웠던 점 등을 작성합니다.)

<br />

## :: 기타 질문 및 특이 사항
-  EXISTS문을 통해 찜목록에 제품이 있는지 확인하는 과정을 넣었습니다. 하지만 DB는 유니크키로 중복값을 받지 않게 설정하지 않았는데 혹시 유니크키를 추가해야할까요?

2022-09-22 07:31 UTC, bigfanoftim commented
> EXISTS문을 통해 찜목록에 제품이 있는지 확인하는 과정을 넣었습니다. 하지만 DB는 유니크키로 중복값을 받지 않게 설정하지 않았는데 혹시 유니크키를 추가해야할까요?

Unique key를 넣어서 혹시나 하는 상황을 대비하는 것이 옳다고 생각됩니다! 상황 보고 시간나시면 DB PR 올려주시죠~

2022-09-22 07:31 UTC, bigfanoftim commented
이것도 마찬가지로 auth merge 후 다시 푸시해 주세요!

2022-09-23 02:22 UTC, bigfanoftim commented
다영님 리뷰 남겨드린 전부 다 적용되었는지 PR에서 직접 확인 후에 라벨 바꿔주세요.

2022-09-23 04:34 UTC, dyjeong576 commented
수정 요청 사항을 다 반영한 거 같은데 제가 놓친 부분이 있을까요?

2022-09-26 01:04 UTC, bigfanoftim requested changes

2022-09-26 01:04 UTC, bigfanoftim commented on models/productDao.js
> +}
현재 코드에서는 만들어 두신 `checkLike` dao는 활용되지 않는 것처럼 보여집니다.
이미 찜에 담긴 제품에 대해서는 어떻게 처리할지 고민해보시면 좋을 것 같습니다!

2022-09-26 01:04 UTC, bigfanoftim commented
> 수정 요청 사항을 다 반영한 거 같은데 제가 놓친 부분이 있을까요?

이 부분은 auth 코드에 관한 코멘트였습니다!

2022-09-26 03:59 UTC, dyjeong576 commented on models/productDao.js
> +}
적용했습니다!

2022-09-26 08:40 UTC, bigfanoftim approved these changes
LGTM 👍

2022-09-26 08:41 UTC, merged